# This file was generated by GoReleaser. DO NOT EDIT.
cask "turo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "766e50fbcdd324b1aa865304c96ae819accfb19abceb7546575832086aa1920b"
      url "https://github.com/kdeps/turo/releases/download/v#{version}/turo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca1134ae7fc9ecae031fb353516dcd1ad97d78bf7f7abd1e074fc6019471cf3d"
      url "https://github.com/kdeps/turo/releases/download/v#{version}/turo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9887aea2d93a26600d7a2829aeab449e8ad6e45e41d893069bf7db508c3d9b98"
      url "https://github.com/kdeps/turo/releases/download/v#{version}/turo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a032aa97a97eb4fc05eb4b817e0c0db3379661ecfa64ab60979eb72222a4d8c3"
      url "https://github.com/kdeps/turo/releases/download/v#{version}/turo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "turo"
  desc "Point more. Token less. Reduce text to its content words to cut input tokens."
  homepage "https://github.com/kdeps/turo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "turo"

  # No zap stanza required

end
