# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdeps < Formula
  desc "Kdeps is a framework for creating dockerized AI Agent APIs"
  homepage "https://kdeps.com"
  version "2.51.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdeps/kdeps/releases/download/v2.51.1/kdeps_Darwin_x86_64.tar.gz"
      sha256 "1236dcc6eacb3afacedf3ecb2a132511a590292f37be8d926cd6541ed3f1ee29"

      define_method(:install) do
        bin.install "kdeps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdeps/kdeps/releases/download/v2.51.1/kdeps_Darwin_arm64.tar.gz"
      sha256 "74502dd16991af263e439cc472e69a4290911642a75ef8636b333dd461229ab6"

      define_method(:install) do
        bin.install "kdeps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdeps/kdeps/releases/download/v2.51.1/kdeps_Linux_x86_64.tar.gz"
      sha256 "3488d656e5ad967b663f123f350cd79dcf2b13dc26eaab1fabdd5e2208f6bf80"
      define_method(:install) do
        bin.install "kdeps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdeps/kdeps/releases/download/v2.51.1/kdeps_Linux_arm64.tar.gz"
      sha256 "a138d4ae096518c04d1b96f59eb696aab52b93d857d0be890b4a7a840c56c4bc"
      define_method(:install) do
        bin.install "kdeps"
      end
    end
  end
end
