# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turo < Formula
  desc "Point more. Token less. Reduce text to its content words to cut input tokens."
  homepage "https://github.com/kdeps/turo"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdeps/turo/releases/download/v0.9.0/turo_Darwin_x86_64.tar.gz"
      sha256 "777519dee4ea953a6baeb6d4939523cf3324995a10caae02f88fe6201219c67b"

      define_method(:install) do
        bin.install "turo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdeps/turo/releases/download/v0.9.0/turo_Darwin_arm64.tar.gz"
      sha256 "3462e6a9453e68d4a30be8289a9e6e54010f9dc65b40690bace9ace06a865fdd"

      define_method(:install) do
        bin.install "turo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdeps/turo/releases/download/v0.9.0/turo_Linux_x86_64.tar.gz"
      sha256 "3b81f7a48c76769fbb4135f3e73705deef21f244943fb1e8512085712b7fffba"
      define_method(:install) do
        bin.install "turo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdeps/turo/releases/download/v0.9.0/turo_Linux_arm64.tar.gz"
      sha256 "0d045777b3bc982c28c017d302f7ff95393f536e669861077a9f82095635af08"
      define_method(:install) do
        bin.install "turo"
      end
    end
  end
end
