# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turo < Formula
  desc "Point more. Token less. Reduce text to its content words to cut input tokens."
  homepage "https://github.com/kdeps/turo"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kdeps/turo/releases/download/v0.4.0/turo_Darwin_x86_64.tar.gz"
      sha256 "a50774d163e2c6a587dbcf471770d1c88b3a33bf679a693e91232e7df62131bf"

      define_method(:install) do
        bin.install "turo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kdeps/turo/releases/download/v0.4.0/turo_Darwin_arm64.tar.gz"
      sha256 "64c84deab952ef0b98be66115b16db7a1ad56226e0fd8ed29bcccfd850f31ba9"

      define_method(:install) do
        bin.install "turo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdeps/turo/releases/download/v0.4.0/turo_Linux_x86_64.tar.gz"
      sha256 "bc44dbc19afacc811852933a5cf31c55cbfbe518e38038016323a22bf5db6058"
      define_method(:install) do
        bin.install "turo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kdeps/turo/releases/download/v0.4.0/turo_Linux_arm64.tar.gz"
      sha256 "f8629592ca53ce73575e17424ae39b25eec93bf27bbfdd15a84afdf28692832f"
      define_method(:install) do
        bin.install "turo"
      end
    end
  end
end
